#!/usr/bin/env php
<?php
require_once(dirname(__FILE__) . '/vendor/autoload.php');
use Symfony\Component\Console\Application;

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->safeLoad();

$application = new Application();

$commands = [
    new \Mintopia\Aoc2022\Meta\RunAll(),
    new \Mintopia\Aoc2022\Meta\RunLatest(),
    new \Mintopia\Aoc2022\Meta\MakeDay(),
    new \Mintopia\Aoc2022\Meta\MakeInput(),
];
for ($i = 1; $i <= 25; $i++) {
    $className = "\\Mintopia\\Aoc2022\\Day{$i}";
    if (class_exists($className)) {
        $commands[] = new $className;
    }
}

$application->addCommands($commands);

$application->setName("Mintopia's Advent of Code 2022");

$application->run();