version: '3'
services:
  aoc:
    image: 1and1internet/php-build-environment:8.2
    volumes:
      - .:/app
    entrypoint: php aoc
  composer:
    image: 1and1internet/php-build-environment:8.2
    entrypoint: composer
    volumes:
      - .:/app